# GENERATED by compose.py boot {{ROLE}}. DO NOT EDIT.
# Regenerate: python references/scripts/compose.py boot {{ROLE}}
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$repoRoot = git rev-parse --show-toplevel
Set-Location $repoRoot

# Parse --name flag (optional override for agent alias)
$AgentName = ""
for ($i = 0; $i -lt $args.Count; $i++) {
    if ($args[$i] -eq "--name" -and ($i + 1) -lt $args.Count) {
        $AgentName = $args[$i + 1]
        break
    }
}

# Read alias from config if no --name override
if (-not $AgentName) {
    $Alias = ""
    try {
        $Alias = (python references/scripts/config.py alias {{ROLE}} 2>$null).Trim()
    } catch {}
    if (-not $Alias) { $Alias = "{{ROLE}}" }
    $AgentName = "SquidSquad - $Alias"
}

if (Test-Path .squidsquad) {
    $config = Get-Content .squidsquad/config.md -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
    $v = if ($config -match '(\d+\.\d+[\.\d]*)') { $Matches[1] } else { '?' }

    # ANSI color: bold red for banner, reset after
    $e = [char]27
    $R = ""; $N = ""
    if ($env:WT_SESSION -or $env:TERM_PROGRAM -eq "vscode" -or $Host.UI.SupportsVirtualTerminal) {
        $R = "${e}[1;31m"; $N = "${e}[0m"
    }

    Write-Host ""
    Write-Host "${R} ____ ____ _  _ _ ___  ____ ____ _  _ ____ ___"
    Write-Host " [__  |  | |  | | |  \ [__  |  | |  | |__| |  \"
    Write-Host " ___] |_\| |__| | |__/ ___] |_\| |__| |  | |__/${N}"
    Write-Host "  S Q U I D S Q U A D   v$v  -  $AgentName"
    Write-Host ""
}

# Inject permissions from template into settings.json
$injectScript = Join-Path $repoRoot ".squidsquad/inject-permissions.ps1"
if (Test-Path $injectScript) { & $injectScript }

# Register this agent in config.md
try { python references/scripts/config.py sync-agents 2>$null } catch {}

# Initialize state bus worktree if state_bus.py exists
$stateBusScript = Join-Path $repoRoot "references/scripts/state_bus.py"
if (Test-Path $stateBusScript) {
    try { python $stateBusScript init 2>$null } catch {}
}

# Set env var for statusline
$env:SQUIDSQUAD_ROLE = "{{ROLE}}"

# --- File paths ---
$RoleDir = Join-Path $repoRoot ".squidsquad/{{ROLE}}"
$PidFile = "$RoleDir/.pid"
$RestartSentinel = "$RoleDir/.restart"
$StateFile = "$RoleDir/current-state"
$HealthFile = "$RoleDir/.health"

if (-not (Test-Path $RoleDir)) { New-Item -ItemType Directory -Path $RoleDir -Force | Out-Null }

# --- Helper: atomic write to .health ---
function Write-Health($status) {
    [System.IO.File]::WriteAllText("$HealthFile.tmp", $status)
    Move-Item -Force "$HealthFile.tmp" $HealthFile -ErrorAction SilentlyContinue
}

# --- PID lock: singleton (must be first — before pre-flight to prevent TOCTOU race #2694) ---
if (Test-Path $PidFile) {
    $oldPid = (Get-Content $PidFile -ErrorAction SilentlyContinue).Trim()
    if ($oldPid -and (Get-Process -Id $oldPid -ErrorAction SilentlyContinue)) {
        Write-Health "error|already running (PID $oldPid)"
        Write-Host "[SquidSquad] Agent {{ROLE}} already running (PID $oldPid). Aborting."
        exit 1
    }
    Remove-Item $PidFile -Force -ErrorAction SilentlyContinue
}
$PID > $PidFile

# --- Pre-flight checks ---
Write-Health "booting"
Write-Host "[SquidSquad] Pre-flight checks..."

$ghCheck = gh auth status 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Health "error|gh auth failed"
    Write-Host "[SquidSquad] FATAL: gh auth check failed. Run 'gh auth login' with 'repo' scope."
    exit 1
}

$WorkingBranch = try { (python references/scripts/config.py get working-branch 2>$null).Trim() } catch { "main" }
if (-not $WorkingBranch) { $WorkingBranch = "main" }
$CurrentBranch = (git branch --show-current 2>$null).Trim()
if ($CurrentBranch -ne $WorkingBranch) {
    Write-Host "[SquidSquad] Switching to working branch '$WorkingBranch'..."
    git checkout $WorkingBranch 2>$null
    if ((git branch --show-current 2>$null).Trim() -ne $WorkingBranch) {
        # Untracked files may conflict with tracked files on the target branch
        # (e.g. .backlog-cache, scan-index.db regenerated at runtime). Force checkout.
        Write-Host "[SquidSquad] Checkout blocked by local files, retrying with force..."
        git checkout -f $WorkingBranch 2>$null
    }
    if ((git branch --show-current 2>$null).Trim() -ne $WorkingBranch) {
        Write-Health "error|wrong branch"
        Write-Host "[SquidSquad] FATAL: Could not switch to '$WorkingBranch'."
        exit 1
    }
}

# Pull latest from remote so agents never run on stale code
Write-Host "[SquidSquad] Pulling latest '$WorkingBranch'..."
git pull --ff-only origin $WorkingBranch 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "[SquidSquad] WARNING: git pull failed (diverged?). Continuing on local HEAD."
}

Write-Host "[SquidSquad] Pre-flight OK."

# --- Heartbeat background job: write epoch every 5s ---
$heartbeatJob = Start-Job -ScriptBlock {
    param($healthFile)
    while ($true) {
        $epoch = [int][double]::Parse((Get-Date -UFormat %s))
        [System.IO.File]::WriteAllText("$healthFile.tmp", "$epoch")
        Move-Item -Force "$healthFile.tmp" $healthFile -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 5
    }
} -ArgumentList (Join-Path $repoRoot ".squidsquad/{{ROLE}}/.health")

# --- Cleanup on exit ---
$cleanupBlock = {
    if ($heartbeatJob) { Stop-Job $heartbeatJob -ErrorAction SilentlyContinue; Remove-Job $heartbeatJob -ErrorAction SilentlyContinue }
    Remove-Item $PidFile -Force -ErrorAction SilentlyContinue
    Write-Health "dead"
}

try {
    # --- Spawn claude ---
    Set-Content -Path $StateFile -Value "idle|Initializing..."

    $claudeProcess = Start-Process -FilePath "claude.exe" `
        -ArgumentList "--dangerously-skip-permissions", "--name", "`"$AgentName`"", "--append-system-prompt", "`"SQUIDSQUAD_ROLE={{ROLE}}`"", "start the loop" `
        -NoNewWindow -PassThru

    $claudeProcess.WaitForExit()
    $exitCode = $claudeProcess.ExitCode

    # --- Check restart sentinel ---
    if (Test-Path $RestartSentinel) {
        $reason = (Get-Content $RestartSentinel -ErrorAction SilentlyContinue).Trim()
        Remove-Item $RestartSentinel -Force -ErrorAction SilentlyContinue
        Write-Host "[SquidSquad] Restart requested: $reason. Respawning..."
        Set-Content -Path $StateFile -Value "restarting|$reason"
        Start-Sleep -Seconds 2

        $claudeProcess = Start-Process -FilePath "claude.exe" `
            -ArgumentList "--dangerously-skip-permissions", "--name", "`"$AgentName`"", "--append-system-prompt", "`"SQUIDSQUAD_ROLE={{ROLE}}`"", "start the loop" `
            -NoNewWindow -PassThru
        $claudeProcess.WaitForExit()
    }

    # --- One crash retry (runtime < 30s) ---
    if ($exitCode -ne 0) {
        # Simple retry — wrapper exits after this
        Write-Host "[SquidSquad] Crash detected (exit $exitCode). One retry..."
        Start-Sleep -Seconds 2

        $claudeProcess = Start-Process -FilePath "claude.exe" `
            -ArgumentList "--dangerously-skip-permissions", "--name", "`"$AgentName`"", "--append-system-prompt", "`"SQUIDSQUAD_ROLE={{ROLE}}`"", "start the loop" `
            -NoNewWindow -PassThru
        $claudeProcess.WaitForExit()
    }

    Write-Host "[SquidSquad] Agent {{ROLE}} exited. Wrapper stopping."
} finally {
    & $cleanupBlock
}
