#!/bin/bash
# GENERATED by compose.py boot {{ROLE}}. DO NOT EDIT.
# Regenerate: python references/scripts/compose.py boot {{ROLE}}
cd "$(git rev-parse --show-toplevel)"

# Parse --name flag (optional override for agent alias)
AGENT_NAME=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) AGENT_NAME="$2"; shift 2 ;;
    *) shift ;;
  esac
done

# Read alias from config if no --name override
if [ -z "$AGENT_NAME" ]; then
  ALIAS=$(python references/scripts/config.py alias {{ROLE}} 2>/dev/null || echo "{{ROLE}}")
  AGENT_NAME="SquidSquad - ${ALIAS}"
fi

if [ -d .squidsquad ]; then
  V=$(grep -o '[0-9][0-9.]*[0-9]' .squidsquad/config.md 2>/dev/null | head -1)
  cat << LOGO

      ▗▄▖
     ▟█ █▙
    ▐█• •█▌
   ███████
   ▐█████▌
    ▐▌▐▌▐▌
  S Q U I D S Q U A D   v${V:-?}  —  ${AGENT_NAME}

LOGO
fi

# Inject permissions from template into settings.json
[ -x .squidsquad/inject-permissions.sh ] && bash .squidsquad/inject-permissions.sh

# Register this agent in config.md
python references/scripts/config.py sync-agents 2>/dev/null || true

# Set env var for statusline (session-scoped, no cross-agent clobber)
export SQUIDSQUAD_ROLE="{{ROLE}}"

# --- PID lock: prevent double-start ---
ROLE_DIR=".squidsquad/{{ROLE}}"
PID_FILE="$ROLE_DIR/.pid"
STOP_FILE="$ROLE_DIR/.stop"
RESTART_LOG="$ROLE_DIR/restart-log.txt"
STATE_FILE="$ROLE_DIR/current-state"
HEALTH_FILE="$ROLE_DIR/.health"

mkdir -p "$ROLE_DIR"

# --- Helper: atomic write to .health (write .tmp then rename) ---
write_health() {
  echo -n "$1" > "$HEALTH_FILE.tmp"
  mv -f "$HEALTH_FILE.tmp" "$HEALTH_FILE"
}

# --- Pre-flight checks: validate environment before entering restart loop ---
write_health "booting"
echo "[SquidSquad] Pre-flight checks..."

# Check gh auth
if ! gh auth status >/dev/null 2>&1; then
  write_health "error|gh auth failed"
  echo "[SquidSquad] FATAL: gh auth check failed. Run 'gh auth login' with 'repo' scope."
  echo "[SquidSquad] .health written: error|gh auth failed"
  exit 1
fi

# Check git branch is main
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null)
if [ "$CURRENT_BRANCH" != "main" ]; then
  write_health "error|wrong branch: $CURRENT_BRANCH (expected main)"
  echo "[SquidSquad] FATAL: Expected branch 'main', got '$CURRENT_BRANCH'."
  echo "[SquidSquad] .health written: error|wrong branch: $CURRENT_BRANCH (expected main)"
  exit 1
fi

echo "[SquidSquad] Pre-flight OK (gh auth + branch main)."

if [ -f "$PID_FILE" ]; then
  OLD_PID=$(cat "$PID_FILE" 2>/dev/null)
  if [ -n "$OLD_PID" ] && kill -0 "$OLD_PID" 2>/dev/null; then
    echo "[SquidSquad] Agent {{ROLE}} already running (PID $OLD_PID). Aborting."
    echo "[SquidSquad] If this is stale, remove $PID_FILE manually."
    write_health "error|already running (PID $OLD_PID)"
    exit 1
  fi
  # Stale PID — clean up
  rm -f "$PID_FILE"
fi
echo $$ > "$PID_FILE"

# --- Cleanup trap: remove PID file on any exit, write .health dead ---
CHILD_PID=""
cleanup() {
  [ -n "$CHILD_PID" ] && kill "$CHILD_PID" 2>/dev/null || true
  rm -f "$PID_FILE"
  # Write final health state if not already error/dead
  if [ -f "$HEALTH_FILE" ]; then
    CURRENT_HEALTH=$(head -1 "$HEALTH_FILE" 2>/dev/null)
    case "$CURRENT_HEALTH" in
      error*|dead) ;;  # Already set — don't overwrite
      *) write_health "dead" ;;
    esac
  else
    write_health "dead"
  fi
}
trap cleanup EXIT

# --- Double Ctrl+C handling: first breaks child, second breaks wrapper ---
LAST_SIGINT=0
on_sigint() {
  NOW=$(date +%s)
  if [ $((NOW - LAST_SIGINT)) -lt 5 ]; then
    echo ""
    echo "[SquidSquad] Double Ctrl+C — stopping wrapper."
    echo "stopped|Agent stopped by user" > "$STATE_FILE"
    write_health "dead"
    exit 0
  fi
  LAST_SIGINT=$NOW
  echo ""
  echo "[SquidSquad] Ctrl+C received. Press again within 5s to stop wrapper, or wait for claude to exit."
  [ -n "$CHILD_PID" ] && kill -INT "$CHILD_PID" 2>/dev/null || true
}
trap on_sigint INT
trap 'echo "[SquidSquad] SIGTERM — stopping."; exit 0' TERM

# --- Auto-restart wrapper (crash recovery only — lifecycle managed by watchdog) ---
MAX_RESTARTS=50
RESTART_COUNT=0
COOLDOWN_BASE=2
COOLDOWN_MAX=300
MIN_RUNTIME_SECONDS=120

while true; do
  # Reset status bar for a fresh session
  rm -f "$STATE_FILE"
  echo "idle|Initializing..." > "$STATE_FILE"

  write_health "alive"

  START_TIME=$(date +%s)

  claude --dangerously-skip-permissions --name "$AGENT_NAME" --append-system-prompt "SQUIDSQUAD_ROLE={{ROLE}}" "start the loop" &
  CHILD_PID=$!

  wait "$CHILD_PID"
  EXIT_CODE=$?
  CHILD_PID=""

  END_TIME=$(date +%s)
  RUNTIME=$((END_TIME - START_TIME))

  # Check for stop sentinel file
  if [ -f "$STOP_FILE" ]; then
    echo "[SquidSquad] Stop file detected. Not restarting."
    rm -f "$STOP_FILE"
    echo "stopped|Agent stopped by user" > "$STATE_FILE"
    write_health "dead"
    break
  fi

  # Append restart log entry: timestamp | exit_code | restart_count | runtime
  TS=$(date '+%Y-%m-%d %H:%M:%S')
  echo "$TS | exit=$EXIT_CODE | restart=$((RESTART_COUNT + 1)) | runtime=${RUNTIME}s" >> "$RESTART_LOG"

  RESTART_COUNT=$((RESTART_COUNT + 1))
  if [ "$RESTART_COUNT" -ge "$MAX_RESTARTS" ]; then
    echo "[SquidSquad] Max restarts ($MAX_RESTARTS) reached. Stopping."
    echo "error|Max restarts reached" > "$STATE_FILE"
    write_health "error|Max restarts reached"
    break
  fi

  write_health "backoff"

  if [ "$RUNTIME" -lt "$MIN_RUNTIME_SECONDS" ]; then
    # Fast crash — exponential backoff
    COOLDOWN=$((COOLDOWN_BASE * (1 << (RESTART_COUNT - 1))))
    [ "$COOLDOWN" -gt "$COOLDOWN_MAX" ] && COOLDOWN=$COOLDOWN_MAX
    echo "[SquidSquad] Fast exit (${RUNTIME}s, exit $EXIT_CODE). Backoff ${COOLDOWN}s..."
    echo "waiting|Restart backoff (${COOLDOWN}s)" > "$STATE_FILE"
    sleep "$COOLDOWN"
  else
    # Healthy run — reset counter, standard 10s cooldown
    RESTART_COUNT=0
    echo "[SquidSquad] Agent exited after ${RUNTIME}s (exit $EXIT_CODE). Restarting in 10s..."
    echo "restarting|Restarting in 10s..." > "$STATE_FILE"
    sleep 10
  fi
done
