#!/bin/bash
# GENERATED by compose.py boot {{ROLE}}. DO NOT EDIT.
# Regenerate: python references/scripts/compose.py boot {{ROLE}}
cd "$(git rev-parse --show-toplevel)"

# Parse --name flag (optional override for agent alias)
AGENT_NAME=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) AGENT_NAME="$2"; shift 2 ;;
    *) shift ;;
  esac
done

# Read alias from config if no --name override
if [ -z "$AGENT_NAME" ]; then
  ALIAS=$(python references/scripts/config.py alias {{ROLE}} 2>/dev/null || echo "{{ROLE}}")
  AGENT_NAME="SquidSquad - ${ALIAS}"
fi

if [ -d .squidsquad ]; then
  V=$(grep -o '[0-9][0-9.]*[0-9]' .squidsquad/config.md 2>/dev/null | head -1)
  _R="" _N=""
  if [ -t 1 ] && [ "$(tput colors 2>/dev/null)" -ge 8 ] 2>/dev/null; then
    _R=$'\e[1;31m' _N=$'\e[0m'
  fi
  echo ""
  echo "${_R} ____ ____ _  _ _ ___  ____ ____ _  _ ____ ___"
  echo " [__  |  | |  | | |  \\ [__  |  | |  | |__| |  \\"
  echo " ___] |_\\| |__| | |__/ ___] |_\\| |__| |  | |__/${_N}"
  echo "  S Q U I D S Q U A D   v${V:-?}  —  ${AGENT_NAME}"
  echo ""
fi

# Inject permissions from template into settings.json
[ -x .squidsquad/inject-permissions.sh ] && bash .squidsquad/inject-permissions.sh

# Register this agent in config.md
python references/scripts/config.py sync-agents 2>/dev/null || true

# Initialize state bus worktree if state_bus.py exists
if [ -f references/scripts/state_bus.py ]; then
  python references/scripts/state_bus.py init 2>/dev/null || true
fi

# Set env var for statusline (session-scoped, no cross-agent clobber)
export SQUIDSQUAD_ROLE="{{ROLE}}"

# --- File paths ---
ROLE_DIR=".squidsquad/{{ROLE}}"
PID_FILE="$ROLE_DIR/.pid"
RESTART_SENTINEL="$ROLE_DIR/.restart"
STATE_FILE="$ROLE_DIR/current-state"
HEALTH_FILE="$ROLE_DIR/.health"

mkdir -p "$ROLE_DIR"

# --- Helper: atomic write to .health ---
write_health() {
  echo -n "$1" > "$HEALTH_FILE.tmp"
  mv -f "$HEALTH_FILE.tmp" "$HEALTH_FILE"
}

# --- PID lock: singleton (must be first — before pre-flight to prevent TOCTOU race #2694) ---
if [ -f "$PID_FILE" ]; then
  OLD_PID=$(cat "$PID_FILE" 2>/dev/null)
  if [ -n "$OLD_PID" ] && kill -0 "$OLD_PID" 2>/dev/null; then
    echo "[SquidSquad] Agent {{ROLE}} already running (PID $OLD_PID). Aborting."
    write_health "error|already running (PID $OLD_PID)"
    exit 1
  fi
  rm -f "$PID_FILE"
fi
echo $$ > "$PID_FILE"

# --- Pre-flight checks ---
write_health "booting"
echo "[SquidSquad] Pre-flight checks..."

if ! gh auth status >/dev/null 2>&1; then
  write_health "error|gh auth failed"
  echo "[SquidSquad] FATAL: gh auth check failed. Run 'gh auth login' with 'repo' scope."
  exit 1
fi

WORKING_BRANCH=$(python references/scripts/config.py get working-branch 2>/dev/null || echo "main")
WORKING_BRANCH=${WORKING_BRANCH:-main}
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null)
if [ "$CURRENT_BRANCH" != "$WORKING_BRANCH" ]; then
  echo "[SquidSquad] Switching to working branch '$WORKING_BRANCH'..."
  if ! git checkout "$WORKING_BRANCH" 2>/dev/null; then
    # Untracked files may conflict with tracked files on the target branch
    # (e.g. .backlog-cache, scan-index.db regenerated at runtime). Force checkout.
    echo "[SquidSquad] Checkout blocked by local files, retrying with force..."
    git checkout -f "$WORKING_BRANCH" 2>/dev/null || git checkout -b "$WORKING_BRANCH" "origin/$WORKING_BRANCH" 2>/dev/null
  fi
  if [ "$(git branch --show-current 2>/dev/null)" != "$WORKING_BRANCH" ]; then
    write_health "error|wrong branch"
    echo "[SquidSquad] FATAL: Could not switch to '$WORKING_BRANCH'."
    exit 1
  fi
fi

# Pull latest from remote so agents never run on stale code
echo "[SquidSquad] Pulling latest '$WORKING_BRANCH'..."
if ! git pull --ff-only origin "$WORKING_BRANCH" 2>/dev/null; then
  echo "[SquidSquad] WARNING: git pull failed (diverged?). Continuing on local HEAD."
fi

echo "[SquidSquad] Pre-flight OK."

# --- Cleanup trap ---
CHILD_PID=""
HEARTBEAT_PID=""
cleanup() {
  [ -n "$CHILD_PID" ] && kill "$CHILD_PID" 2>/dev/null || true
  [ -n "$HEARTBEAT_PID" ] && kill "$HEARTBEAT_PID" 2>/dev/null || true
  rm -f "$PID_FILE"
  write_health "dead"
}
trap cleanup EXIT

# --- Double Ctrl+C handling ---
LAST_SIGINT=0
on_sigint() {
  NOW=$(date +%s)
  if [ $((NOW - LAST_SIGINT)) -lt 5 ]; then
    echo ""
    echo "[SquidSquad] Double Ctrl+C — stopping."
    echo "stopped|Agent stopped by user" > "$STATE_FILE"
    exit 0
  fi
  LAST_SIGINT=$NOW
  echo ""
  echo "[SquidSquad] Ctrl+C received. Press again within 5s to stop, or wait for claude to exit."
  [ -n "$CHILD_PID" ] && kill -INT "$CHILD_PID" 2>/dev/null || true
}
trap on_sigint INT
trap 'echo "[SquidSquad] SIGTERM — stopping."; exit 0' TERM

# --- Heartbeat background job: write epoch every 5s ---
(
  while true; do
    date +%s > "$HEALTH_FILE.tmp"
    mv -f "$HEALTH_FILE.tmp" "$HEALTH_FILE"
    sleep 5
  done
) &
HEARTBEAT_PID=$!

# --- Sentinel paths ---
STOP_SENTINEL="$ROLE_DIR/.stop"
STOP_AFTER_CYCLE_SENTINEL="$ROLE_DIR/.stop-after-cycle"

# --- Wrapper loop: respawn indefinitely, .stop is the only brake ---
CONSECUTIVE_CRASHES=0
MAX_CRASHES=5

while true; do
  rm -f "$STATE_FILE"
  echo "idle|Initializing..." > "$STATE_FILE"

  claude --dangerously-skip-permissions --name "$AGENT_NAME" --append-system-prompt "SQUIDSQUAD_ROLE={{ROLE}}" "start the loop" &
  CHILD_PID=$!

  wait "$CHILD_PID"
  EXIT_CODE=$?
  CHILD_PID=""

  # --- Check .stop-after-cycle sentinel (new universal mechanism) ---
  if [ -f "$STOP_AFTER_CYCLE_SENTINEL" ]; then
    REASON=$(cat "$STOP_AFTER_CYCLE_SENTINEL" 2>/dev/null || echo "unknown")
    rm -f "$STOP_AFTER_CYCLE_SENTINEL"

    # If .stop also exists, exit permanently
    if [ -f "$STOP_SENTINEL" ]; then
      echo "[SquidSquad] .stop-after-cycle + .stop detected. Agent {{ROLE}} stopped permanently."
      break
    fi

    echo "[SquidSquad] .stop-after-cycle: $REASON. Respawning..."
    write_health "restarting"
    echo "restarting|$REASON" > "$STATE_FILE"
    CONSECUTIVE_CRASHES=0
    sleep 2
    continue
  fi

  # --- Check legacy .restart sentinel (backward compat — remove next version) ---
  if [ -f "$RESTART_SENTINEL" ]; then
    REASON=$(cat "$RESTART_SENTINEL" 2>/dev/null || echo "unknown")
    rm -f "$RESTART_SENTINEL"
    echo "[SquidSquad] DEPRECATED: .restart sentinel detected. Use .stop-after-cycle instead. Respawning..."
    write_health "restarting"
    echo "restarting|$REASON" > "$STATE_FILE"
    CONSECUTIVE_CRASHES=0
    sleep 2
    continue
  fi

  # --- Clean exit without sentinel: wrapper stops ---
  if [ "$EXIT_CODE" -eq 0 ]; then
    echo "[SquidSquad] Agent {{ROLE}} exited cleanly (no sentinel). Wrapper stopping."
    break
  fi

  # --- Crash handling with exponential backoff ---
  CONSECUTIVE_CRASHES=$((CONSECUTIVE_CRASHES + 1))
  if [ "$CONSECUTIVE_CRASHES" -ge "$MAX_CRASHES" ]; then
    echo "[SquidSquad] Agent {{ROLE}} crashed $CONSECUTIVE_CRASHES times consecutively. Writing .stop and exiting."
    write_health "error|$CONSECUTIVE_CRASHES consecutive crashes"
    echo "auto-stopped after $CONSECUTIVE_CRASHES crashes" > "$STOP_SENTINEL"
    break
  fi

  BACKOFF=$((2 ** CONSECUTIVE_CRASHES))
  [ "$BACKOFF" -gt 300 ] && BACKOFF=300
  echo "[SquidSquad] Crash detected (exit $EXIT_CODE, attempt $CONSECUTIVE_CRASHES/$MAX_CRASHES). Retrying in ${BACKOFF}s..."
  write_health "backoff"
  sleep "$BACKOFF"
done

echo "[SquidSquad] Wrapper for {{ROLE}} exiting."
