"""Drift detection for references/agent-instructions.md (#9746).

The canonical reference template is generated by `python references/scripts/compose.py all`.
If the source sub-skills change but agent-instructions.md is not regenerated, humans/tools
reading the canonical template get stale instructions (AUDIT-B Risk 1).

This test re-runs compose_all() and asserts the on-disk file matches. Failure means
agent-instructions.md needs regeneration via `python references/scripts/compose.py all`.
"""

import sys
from pathlib import Path

import pytest

SCRIPTS = Path(__file__).resolve().parent.parent / "references" / "scripts"
sys.path.insert(0, str(SCRIPTS))

import compose

CANONICAL = Path(__file__).resolve().parent.parent / "references" / "agent-instructions.md"


class TestAgentInstructionsDriftDetection:
    """#9746: references/agent-instructions.md must match fresh compose_all() output."""

    def test_canonical_template_exists(self):
        assert CANONICAL.exists(), (
            f"{CANONICAL} not found. Regenerate with: "
            "python references/scripts/compose.py all"
        )

    def test_canonical_template_matches_fresh_compose(self):
        """If this fails, run: python references/scripts/compose.py all"""
        fresh = compose.compose_all()
        on_disk = CANONICAL.read_text(encoding="utf-8")
        assert fresh == on_disk, (
            "references/agent-instructions.md is out of sync with the source "
            "sub-skills. Regenerate with: "
            "python references/scripts/compose.py all"
        )

    def test_no_branch_workflow_references(self):
        """Regression: #9478 removed branch_workflow; canonical template must not bring it back."""
        text = CANONICAL.read_text(encoding="utf-8")
        # Only descriptive comments are allowed per #9478 CONTEXT §3 grep clause.
        # But since compose_all() emits the same content as the deployed CLAUDE.md
        # files (which are verified clean by #9478), this should be empty.
        lower = text.lower()
        assert "branch-workflow" not in lower
        assert "branch workflow" not in lower
        assert "branch_workflow" not in lower

    def test_has_boot_bootstrap_section(self):
        """Regression: #9588 introduced the boot-bootstrap sub-skill; must be inlined."""
        text = CANONICAL.read_text(encoding="utf-8")
        assert "<!-- sub-skill: boot-bootstrap -->" in text
        assert "## Boot — Mode Detection (#9588)" in text
