#!/bin/bash
# GENERATED by compose.py boot pm. DO NOT EDIT.
# Regenerate: python references/scripts/compose.py boot pm
cd "$(git rev-parse --show-toplevel)"

# Parse --name flag (optional override for agent alias)
AGENT_NAME=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) AGENT_NAME="$2"; shift 2 ;;
    *) shift ;;
  esac
done

# Read alias from config if no --name override
if [ -z "$AGENT_NAME" ]; then
  ALIAS=$(python references/scripts/config.py alias pm 2>/dev/null || echo "pm")
  AGENT_NAME="SquidSquad - ${ALIAS}"
fi

if [ -d .squidsquad ]; then
  V=$(grep -o '[0-9][0-9.]*[0-9]' .squidsquad/config.md 2>/dev/null | head -1)
  _R="" _N=""
  if [ -t 1 ] && [ "$(tput colors 2>/dev/null)" -ge 8 ] 2>/dev/null; then
    _R=$'\e[1;31m' _N=$'\e[0m'
  fi
  echo ""
  echo "${_R} ____ ____ _  _ _ ___  ____ ____ _  _ ____ ___"
  echo " [__  |  | |  | | |  \\ [__  |  | |  | |__| |  \\"
  echo " ___] |_\\| |__| | |__/ ___] |_\\| |__| |  | |__/${_N}"
  echo "  S Q U I D S Q U A D   v${V:-?}  —  ${AGENT_NAME}"
  echo ""
fi

# Inject permissions from template into settings.json
[ -x .squidsquad/inject-permissions.sh ] && bash .squidsquad/inject-permissions.sh

# Register this agent in config.md
python references/scripts/config.py sync-agents 2>/dev/null || true

# Initialize state bus worktree if state_bus.py exists
if [ -f references/scripts/state_bus.py ]; then
  python references/scripts/state_bus.py init 2>/dev/null || true
fi

# Set env var for statusline (session-scoped, no cross-agent clobber)
export SQUIDSQUAD_ROLE="pm"

# --- File paths ---
ROLE_DIR=".squidsquad/pm"
PID_FILE="$ROLE_DIR/.pid"
RESTART_SENTINEL="$ROLE_DIR/.restart"
STATE_FILE="$ROLE_DIR/current-state"
HEALTH_FILE="$ROLE_DIR/.health"
CLAUDE_PID_FILE="$ROLE_DIR/.claude-pid"

mkdir -p "$ROLE_DIR"

# --- Helper: atomic write to .health ---
write_health() {
  echo -n "$1" > "$HEALTH_FILE.tmp"
  mv -f "$HEALTH_FILE.tmp" "$HEALTH_FILE"
}

# --- PID lock: singleton (must be first — before pre-flight to prevent TOCTOU race #2694) ---
if [ -f "$PID_FILE" ]; then
  OLD_PID=$(cat "$PID_FILE" 2>/dev/null)
  if [ -n "$OLD_PID" ] && kill -0 "$OLD_PID" 2>/dev/null; then
    echo "[SquidSquad] Agent pm already running (PID $OLD_PID). Aborting."
    write_health "error|already running (PID $OLD_PID)"
    exit 1
  fi
  rm -f "$PID_FILE"
fi
echo $$ > "$PID_FILE"

# --- Pre-flight checks ---
write_health "booting"
echo "[SquidSquad] Pre-flight checks..."

if ! gh auth status >/dev/null 2>&1; then
  write_health "error|gh auth failed"
  echo "[SquidSquad] FATAL: gh auth check failed. Run 'gh auth login' with 'repo' scope."
  exit 1
fi

WORKING_BRANCH=$(python references/scripts/config.py get working-branch 2>/dev/null || echo "main")
WORKING_BRANCH=${WORKING_BRANCH:-main}
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null)
if [ "$CURRENT_BRANCH" != "$WORKING_BRANCH" ]; then
  echo "[SquidSquad] Switching to working branch '$WORKING_BRANCH'..."
  if ! git checkout "$WORKING_BRANCH" 2>/dev/null; then
    # Untracked files may conflict with tracked files on the target branch
    # (e.g. .backlog-cache, scan-index.db regenerated at runtime). Force checkout.
    echo "[SquidSquad] Checkout blocked by local files, retrying with force..."
    git checkout -f "$WORKING_BRANCH" 2>/dev/null || git checkout -b "$WORKING_BRANCH" "origin/$WORKING_BRANCH" 2>/dev/null
  fi
  if [ "$(git branch --show-current 2>/dev/null)" != "$WORKING_BRANCH" ]; then
    write_health "error|wrong branch"
    echo "[SquidSquad] FATAL: Could not switch to '$WORKING_BRANCH'."
    exit 1
  fi
fi

# Pull latest from remote so agents never run on stale code
echo "[SquidSquad] Pulling latest '$WORKING_BRANCH'..."
if ! git pull --ff-only origin "$WORKING_BRANCH" 2>/dev/null; then
  echo "[SquidSquad] WARNING: git pull failed (diverged?). Continuing on local HEAD."
fi

echo "[SquidSquad] Pre-flight OK."

# --- Cleanup trap ---
CHILD_PID=""
HEARTBEAT_PID=""
cleanup() {
  [ -n "$CHILD_PID" ] && kill "$CHILD_PID" 2>/dev/null || true
  [ -n "$HEARTBEAT_PID" ] && kill "$HEARTBEAT_PID" 2>/dev/null || true
  rm -f "$PID_FILE" "$CLAUDE_PID_FILE"
  write_health "dead"
}
trap cleanup EXIT

# --- Double Ctrl+C handling ---
LAST_SIGINT=0
on_sigint() {
  NOW=$(date +%s)
  if [ $((NOW - LAST_SIGINT)) -lt 5 ]; then
    echo ""
    echo "[SquidSquad] Double Ctrl+C — stopping."
    echo "stopped|Agent stopped by user" > "$STATE_FILE"
    exit 0
  fi
  LAST_SIGINT=$NOW
  echo ""
  echo "[SquidSquad] Ctrl+C received. Press again within 5s to stop, or wait for claude to exit."
  [ -n "$CHILD_PID" ] && kill -INT "$CHILD_PID" 2>/dev/null || true
}
trap on_sigint INT
trap 'echo "[SquidSquad] SIGTERM — stopping."; exit 0' TERM

# --- Heartbeat background job: write epoch every 5s ---
(
  while true; do
    date +%s > "$HEALTH_FILE.tmp"
    mv -f "$HEALTH_FILE.tmp" "$HEALTH_FILE"
    sleep 5
  done
) &
HEARTBEAT_PID=$!

# --- Spawn claude ---
HAS_CRASHED=false

rm -f "$STATE_FILE"
echo "idle|Initializing..." > "$STATE_FILE"

claude --dangerously-skip-permissions --name "$AGENT_NAME" --append-system-prompt "SQUIDSQUAD_ROLE=pm" "start the loop" &
CHILD_PID=$!
echo "$CHILD_PID" > "$CLAUDE_PID_FILE"

wait "$CHILD_PID"
EXIT_CODE=$?
CHILD_PID=""
END_EPOCH=$(date +%s)
START_EPOCH=$(cat "$HEALTH_FILE" 2>/dev/null | head -1)
START_EPOCH=${START_EPOCH:-$END_EPOCH}

# --- Check restart sentinel ---
if [ -f "$RESTART_SENTINEL" ]; then
  REASON=$(cat "$RESTART_SENTINEL" 2>/dev/null || echo "unknown")
  rm -f "$RESTART_SENTINEL"
  echo "[SquidSquad] Restart requested: $REASON. Respawning..."
  echo "restarting|$REASON" > "$STATE_FILE"
  sleep 2
  claude --dangerously-skip-permissions --name "$AGENT_NAME" --append-system-prompt "SQUIDSQUAD_ROLE=pm" "start the loop" &
  CHILD_PID=$!
  echo "$CHILD_PID" > "$CLAUDE_PID_FILE"
  wait "$CHILD_PID"
  CHILD_PID=""
fi

# --- One crash retry (if runtime < 30s and no sentinel) ---
if [ "$EXIT_CODE" -ne 0 ] && [ "$HAS_CRASHED" = false ]; then
  RUNTIME=$((END_EPOCH - START_EPOCH))
  if [ "$RUNTIME" -lt 30 ] 2>/dev/null; then
    HAS_CRASHED=true
    echo "[SquidSquad] Crash detected (${RUNTIME}s, exit $EXIT_CODE). One retry..."
    sleep 2
    claude --dangerously-skip-permissions --name "$AGENT_NAME" --append-system-prompt "SQUIDSQUAD_ROLE=pm" "start the loop" &
    CHILD_PID=$!
    echo "$CHILD_PID" > "$CLAUDE_PID_FILE"
    wait "$CHILD_PID"
    CHILD_PID=""
  fi
fi

echo "[SquidSquad] Agent pm exited. Wrapper stopping."
