# GENERATED by compose.py boot dm. DO NOT EDIT.
# Regenerate: python references/scripts/compose.py boot dm
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$repoRoot = git rev-parse --show-toplevel
Set-Location $repoRoot

# Parse --name flag (optional override for agent alias)
$AgentName = ""
for ($i = 0; $i -lt $args.Count; $i++) {
    if ($args[$i] -eq "--name" -and ($i + 1) -lt $args.Count) {
        $AgentName = $args[$i + 1]
        break
    }
}

# Read alias from config if no --name override
if (-not $AgentName) {
    $Alias = ""
    try {
        $Alias = (python references/scripts/config.py alias dm 2>$null).Trim()
    } catch {}
    if (-not $Alias) { $Alias = "dm" }
    $AgentName = "SquidSquad - $Alias"
}

if (Test-Path .squidsquad) {
    $config = Get-Content .squidsquad/config.md -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
    $v = if ($config -match '(\d+\.\d+[\.\d]*)') { $Matches[1] } else { '?' }

    Write-Host ""
    Write-Host "      ▗▄▖"
    Write-Host "     ▟█ █▙"
    Write-Host "    ▐█• •█▌"
    Write-Host "   ███████"
    Write-Host "   ▐█████▌"
    Write-Host "    ▐▌▐▌▐▌"
    Write-Host "  S Q U I D S Q U A D   v$v  -  $AgentName"
    Write-Host ""
}

# Inject permissions from template into settings.json
$injectScript = Join-Path $repoRoot ".squidsquad/inject-permissions.ps1"
if (Test-Path $injectScript) { & $injectScript }

# Register this agent in config.md
try { python references/scripts/config.py sync-agents 2>$null } catch {}

# Set env var for statusline (session-scoped, no cross-agent clobber)
$env:SQUIDSQUAD_ROLE = "dm"

# --- PID lock: prevent double-start ---
$RoleDir = ".squidsquad/dm"
$PidFile = "$RoleDir/.pid"
$StopFile = "$RoleDir/.stop"
$RestartSentinel = "$RoleDir/.restart"
$RestartLog = "$RoleDir/restart-log.txt"
$StateFile = "$RoleDir/current-state"
$PressureFile = "$RoleDir/context-pressure"
$HealthFile = "$RoleDir/.health"

if (-not (Test-Path $RoleDir)) { New-Item -ItemType Directory -Path $RoleDir -Force | Out-Null }

# --- Helper: atomic write to .health (write .tmp then rename) ---
function Write-Health {
    param([string]$Status)
    $tmp = "$HealthFile.tmp"
    [System.IO.File]::WriteAllText((Resolve-Path $RoleDir).Path + "/.health.tmp", $Status)
    Move-Item -Force $tmp $HealthFile -ErrorAction SilentlyContinue
}

# --- Pre-flight checks: validate environment before entering restart loop ---
Write-Health "booting"
Write-Host "[SquidSquad] Pre-flight checks..."

# Check gh auth
$ghStatus = $null
try { $ghStatus = & gh auth status 2>&1 } catch {}
if ($LASTEXITCODE -ne 0) {
    $errMsg = "error|gh auth failed"
    Write-Health $errMsg
    Write-Host "[SquidSquad] FATAL: gh auth check failed. Run 'gh auth login' with 'repo' scope."
    Write-Host "[SquidSquad] .health written: $errMsg"
    exit 1
}

# Check git branch is main
$currentBranch = (git branch --show-current 2>$null).Trim()
if ($currentBranch -ne "main") {
    $errMsg = "error|wrong branch: $currentBranch (expected main)"
    Write-Health $errMsg
    Write-Host "[SquidSquad] FATAL: Expected branch 'main', got '$currentBranch'."
    Write-Host "[SquidSquad] .health written: $errMsg"
    exit 1
}

Write-Host "[SquidSquad] Pre-flight OK (gh auth + branch main)."

if (Test-Path $PidFile) {
    $oldPid = (Get-Content $PidFile -ErrorAction SilentlyContinue | Select-Object -First 1)
    if ($oldPid) {
        $running = $null
        try { $running = Get-Process -Id $oldPid -ErrorAction SilentlyContinue } catch {}
        if ($running) {
            Write-Host "[SquidSquad] Agent dm already running (PID $oldPid). Aborting."
            Write-Host "[SquidSquad] If this is stale, remove $PidFile manually."
            Write-Health "error|already running (PID $oldPid)"
            exit 1
        }
    }
    # Stale — clean up
    Remove-Item $PidFile -ErrorAction SilentlyContinue
}
$PID | Set-Content $PidFile -NoNewline

# --- Cleanup on exit: remove PID file, write .health dead ---
try {
    # --- Auto-restart wrapper ---
    $MaxRestarts = 50
    $RestartCount = 0
    $CooldownBase = 2
    $CooldownMax = 300
    $MinRuntimeSeconds = 120
    $SelfRestartLimit = 3  # max self-restarts per hour

    while ($true) {
        # Reset status bar and context pressure for a fresh session
        Remove-Item $StateFile -ErrorAction SilentlyContinue
        "idle|Initializing..." | Set-Content $StateFile -NoNewline
        Remove-Item $PressureFile -ErrorAction SilentlyContinue

        Write-Health "alive"

        $startTime = Get-Date

        $sysPrompt = "SQUIDSQUAD_ROLE=dm"
        $initMsg = "start the loop"

        # Read context threshold from config (default 70)
        $CtxThreshold = 70
        try {
            $t = (python references/scripts/config.py get context-threshold 2>$null).Trim()
            if ($t -match '^\d+$') { $CtxThreshold = [int]$t }
        } catch {}

        # Start Claude as a background process so we can poll for .restart and context pressure
        # Use cmd /c to launch — claude is a .cmd shim on Windows, Start-Process can't exec .cmd directly
        $claudeProc = Start-Process -FilePath "cmd.exe" -ArgumentList "/c", "claude", "--dangerously-skip-permissions", "--name", "`"`"$AgentName`"`"", "--append-system-prompt", "$sysPrompt", "$initMsg" -NoNewWindow -PassThru

        # Background poller: watch for .restart sentinel AND context pressure
        # Context pressure flow:
        #   1. Agent writes pressure % to context-pressure file (Step 1b, early in cycle)
        #   2. Watcher detects pressure >= threshold
        #   3. Watcher waits for agent to finish cycle (idle| in current-state, max 10 min)
        #   4. Watcher kills process → boot script restarts with fresh context
        $watcherJob = Start-Job -ScriptBlock {
            param($sentinel, $pid, $pressureFile, $stateFile, $threshold)
            $MaxWaitCycle = 600  # 10 minutes max wait for cycle to finish
            while (-not (Get-Process -Id $pid -ErrorAction SilentlyContinue).HasExited) {
                # Check .restart sentinel (agent requested restart)
                if (Test-Path $sentinel) {
                    Write-Output "[SquidSquad] Restart sentinel detected — stopping Claude (PID $pid)..."
                    try { & taskkill /T /F /PID $pid 2>$null } catch {}
                    break
                }
                # Check context pressure
                if (Test-Path $pressureFile) {
                    $raw = (Get-Content $pressureFile -ErrorAction SilentlyContinue | Select-Object -First 1)
                    if ($raw -match '^\d+$') {
                        $pressure = [int]$raw
                        if ($pressure -ge $threshold) {
                            Write-Output "[SquidSquad] Context pressure ${pressure}% >= ${threshold}% — waiting for cycle to finish..."
                            # Wait for agent to finish its current cycle (idle| in current-state)
                            $waited = 0
                            while ($waited -lt $MaxWaitCycle) {
                                if ((Get-Process -Id $pid -ErrorAction SilentlyContinue).HasExited) { break }
                                if (Test-Path $stateFile) {
                                    $state = (Get-Content $stateFile -ErrorAction SilentlyContinue | Select-Object -First 1)
                                    if ($state -match '^idle\|') {
                                        Write-Output "[SquidSquad] Cycle complete — restarting for fresh context..."
                                        break
                                    }
                                }
                                Start-Sleep -Seconds 10
                                $waited += 10
                            }
                            if ($waited -ge $MaxWaitCycle) {
                                Write-Output "[SquidSquad] Timed out waiting for cycle — forcing restart..."
                            }
                            try { & taskkill /T /F /PID $pid 2>$null } catch {}
                            break
                        }
                    }
                }
                Start-Sleep -Seconds 5
            }
        } -ArgumentList $RestartSentinel, $claudeProc.Id, $PressureFile, $StateFile, $CtxThreshold

        $claudeProc.WaitForExit()
        $exitCode = $claudeProc.ExitCode

        # Clean up watcher
        Stop-Job $watcherJob -ErrorAction SilentlyContinue
        Remove-Job $watcherJob -ErrorAction SilentlyContinue

        $runtime = [int]((Get-Date) - $startTime).TotalSeconds

        # Check for stop sentinel file
        if (Test-Path $StopFile) {
            Write-Host "[SquidSquad] Stop file detected. Not restarting."
            Remove-Item $StopFile -ErrorAction SilentlyContinue
            "stopped|Agent stopped by user" | Set-Content $StateFile -NoNewline
            Write-Health "dead"
            break
        }

        # Check for self-restart sentinel (agent requested restart)
        if (Test-Path $RestartSentinel) {
            $reason = (Get-Content $RestartSentinel -ErrorAction SilentlyContinue | Select-Object -First 1)
            if (-not $reason) { $reason = "unknown" }
            Remove-Item $RestartSentinel -ErrorAction SilentlyContinue

            # --- Self-restart rate limit: 3 per hour (hard enforcement) ---
            $selfRestartCount = 0
            $oneHourAgo = (Get-Date).AddHours(-1)
            if (Test-Path $RestartLog) {
                $lines = Get-Content $RestartLog -ErrorAction SilentlyContinue
                foreach ($line in $lines) {
                    if ($line -match "self-restart" -and $line -match "^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})") {
                        try {
                            $entryTime = [datetime]::ParseExact($Matches[1], "yyyy-MM-dd HH:mm:ss", $null)
                            if ($entryTime -gt $oneHourAgo) { $selfRestartCount++ }
                        } catch {}
                    }
                }
            }

            if ($selfRestartCount -ge $SelfRestartLimit) {
                $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
                "$ts | exit=$exitCode | self-restart-BLOCKED | reason=$reason | rate-limit ($SelfRestartLimit/hr exceeded) | runtime=${runtime}s" | Add-Content $RestartLog
                Write-Host "[SquidSquad] Self-restart rate limit ($SelfRestartLimit/hr) exceeded — ignoring .restart sentinel."
                # Continue running — do NOT restart, fall through to normal crash handling
            } else {
                $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
                "$ts | exit=$exitCode | self-restart | reason=$reason | runtime=${runtime}s" | Add-Content $RestartLog
                Write-Host "[SquidSquad] Self-restart requested: $reason. Restarting immediately..."
                Write-Health "restarting"
                "restarting|Self-restart: $reason" | Set-Content $StateFile -NoNewline
                $RestartCount = 0
                Start-Sleep -Seconds 2
                continue
            }
        }

        # Check if this was a context pressure restart
        if (Test-Path $PressureFile) {
            $raw = (Get-Content $PressureFile -ErrorAction SilentlyContinue | Select-Object -First 1)
            if ($raw -match '^\d+$' -and [int]$raw -ge $CtxThreshold) {
                $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
                "$ts | exit=$exitCode | context-pressure | pressure=${raw}% | runtime=${runtime}s" | Add-Content $RestartLog
                Write-Host "[SquidSquad] Context pressure restart (${raw}%). Restarting with fresh context..."
                Write-Health "restarting"
                "restarting|Context pressure ${raw}% — fresh start" | Set-Content $StateFile -NoNewline
                Remove-Item $PressureFile -ErrorAction SilentlyContinue
                $RestartCount = 0
                Start-Sleep -Seconds 2
                continue
            }
        }

        # Append restart log entry
        $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        "$ts | exit=$exitCode | restart=$($RestartCount + 1) | runtime=${runtime}s" | Add-Content $RestartLog

        $RestartCount++
        if ($RestartCount -ge $MaxRestarts) {
            Write-Host "[SquidSquad] Max restarts ($MaxRestarts) reached. Stopping."
            "error|Max restarts reached" | Set-Content $StateFile -NoNewline
            Write-Health "error|Max restarts reached"
            break
        }

        Write-Health "backoff"

        if ($runtime -lt $MinRuntimeSeconds) {
            # Fast crash — exponential backoff
            $cooldown = [Math]::Min($CooldownBase * [Math]::Pow(2, $RestartCount - 1), $CooldownMax)
            $cooldown = [int]$cooldown
            Write-Host "[SquidSquad] Fast exit (${runtime}s, exit $exitCode). Backoff ${cooldown}s..."
            "waiting|Restart backoff (${cooldown}s)" | Set-Content $StateFile -NoNewline
            Start-Sleep -Seconds $cooldown
        } else {
            # Healthy run — reset counter, standard 10s cooldown
            $RestartCount = 0
            Write-Host "[SquidSquad] Agent exited after ${runtime}s (exit $exitCode). Restarting in 10s..."
            "restarting|Restarting in 10s..." | Set-Content $StateFile -NoNewline
            Start-Sleep -Seconds 10
        }
    }
} finally {
    Remove-Item $PidFile -ErrorAction SilentlyContinue
    # Write final health state if not already set to error/dead
    if (Test-Path $HealthFile) {
        $current = Get-Content $HealthFile -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($current -notmatch "^(error|dead)") {
            Write-Health "dead"
        }
    } else {
        Write-Health "dead"
    }
}
