#!/bin/bash
# GENERATED by compose.py boot dm. DO NOT EDIT.
# Regenerate: python references/scripts/compose.py boot dm
cd "$(git rev-parse --show-toplevel)"

# Parse --name flag (optional override for agent alias)
AGENT_NAME=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) AGENT_NAME="$2"; shift 2 ;;
    *) shift ;;
  esac
done

# Read alias from config if no --name override
if [ -z "$AGENT_NAME" ]; then
  ALIAS=$(python references/scripts/config.py alias dm 2>/dev/null || echo "dm")
  AGENT_NAME="SquidSquad - ${ALIAS}"
fi

if [ -d .squidsquad ]; then
  V=$(grep -o '[0-9][0-9.]*[0-9]' .squidsquad/config.md 2>/dev/null | head -1)
  cat << LOGO

      ▗▄▖
     ▟█ █▙
    ▐█• •█▌
   ███████
   ▐█████▌
    ▐▌▐▌▐▌
  S Q U I D S Q U A D   v${V:-?}  —  ${AGENT_NAME}

LOGO
fi

# Inject permissions from template into settings.json
[ -x .squidsquad/inject-permissions.sh ] && bash .squidsquad/inject-permissions.sh

# Register this agent in config.md
python references/scripts/config.py sync-agents 2>/dev/null || true

# Write role for statusline (not used for auto-boot — system prompt handles that)
echo "dm" > .squidsquad/.active-role

# --- PID lock: prevent double-start ---
ROLE_DIR=".squidsquad/dm"
PID_FILE="$ROLE_DIR/.pid"
STOP_FILE="$ROLE_DIR/.stop"
RESTART_SENTINEL="$ROLE_DIR/.restart"
RESTART_LOG="$ROLE_DIR/restart-log.txt"
STATE_FILE="$ROLE_DIR/current-state"

mkdir -p "$ROLE_DIR"

if [ -f "$PID_FILE" ]; then
  OLD_PID=$(cat "$PID_FILE" 2>/dev/null)
  if [ -n "$OLD_PID" ] && kill -0 "$OLD_PID" 2>/dev/null; then
    echo "[SquidSquad] Agent dm already running (PID $OLD_PID). Aborting."
    echo "[SquidSquad] If this is stale, remove $PID_FILE manually."
    exit 1
  fi
  # Stale PID — clean up
  rm -f "$PID_FILE"
fi
echo $$ > "$PID_FILE"

# --- Cleanup trap: remove PID file on any exit, kill child on signal ---
CHILD_PID=""
cleanup() {
  [ -n "$CHILD_PID" ] && kill "$CHILD_PID" 2>/dev/null || true
  rm -f "$PID_FILE"
}
trap cleanup EXIT

# --- Double Ctrl+C handling: first breaks child, second breaks wrapper ---
LAST_SIGINT=0
on_sigint() {
  NOW=$(date +%s)
  if [ $((NOW - LAST_SIGINT)) -lt 5 ]; then
    echo ""
    echo "[SquidSquad] Double Ctrl+C — stopping wrapper."
    echo "stopped|Agent stopped by user" > "$STATE_FILE"
    exit 0
  fi
  LAST_SIGINT=$NOW
  echo ""
  echo "[SquidSquad] Ctrl+C received. Press again within 5s to stop wrapper, or wait for claude to exit."
  [ -n "$CHILD_PID" ] && kill -INT "$CHILD_PID" 2>/dev/null || true
}
trap on_sigint INT
trap 'echo "[SquidSquad] SIGTERM — stopping."; exit 0' TERM

# --- Auto-restart wrapper ---
MAX_RESTARTS=50
RESTART_COUNT=0
COOLDOWN_BASE=2
COOLDOWN_MAX=300
MIN_RUNTIME_SECONDS=120

while true; do
  # Reset status bar for a fresh session
  rm -f "$STATE_FILE"
  echo "idle|Initializing..." > "$STATE_FILE"

  START_TIME=$(date +%s)

  claude --dangerously-skip-permissions --name "$AGENT_NAME" --append-system-prompt "SQUIDSQUAD_ROLE=dm" "start the loop" &
  CHILD_PID=$!

  # Background poller: watch for .restart sentinel while Claude is running (#918)
  (
    while kill -0 "$CHILD_PID" 2>/dev/null; do
      if [ -f "$RESTART_SENTINEL" ]; then
        echo "[SquidSquad] Restart sentinel detected — killing Claude (PID $CHILD_PID)..."
        kill -INT "$CHILD_PID" 2>/dev/null
        break
      fi
      sleep 5
    done
  ) &
  WATCHER_PID=$!

  wait "$CHILD_PID"
  EXIT_CODE=$?
  CHILD_PID=""

  # Clean up watcher
  kill "$WATCHER_PID" 2>/dev/null
  wait "$WATCHER_PID" 2>/dev/null

  END_TIME=$(date +%s)
  RUNTIME=$((END_TIME - START_TIME))

  # Check for stop sentinel file
  if [ -f "$STOP_FILE" ]; then
    echo "[SquidSquad] Stop file detected. Not restarting."
    rm -f "$STOP_FILE"
    echo "stopped|Agent stopped by user" > "$STATE_FILE"
    break
  fi

  # Check for self-restart sentinel (agent requested restart)
  if [ -f "$RESTART_SENTINEL" ]; then
    REASON=$(cat "$RESTART_SENTINEL" 2>/dev/null || echo "unknown")
    rm -f "$RESTART_SENTINEL"
    TS=$(date '+%Y-%m-%d %H:%M:%S')
    echo "$TS | exit=$EXIT_CODE | self-restart | reason=$REASON | runtime=${RUNTIME}s" >> "$RESTART_LOG"
    echo "[SquidSquad] Self-restart requested: $REASON. Restarting immediately..."
    echo "restarting|Self-restart: $REASON" > "$STATE_FILE"
    RESTART_COUNT=0
    sleep 2
    continue
  fi

  # Append restart log entry: timestamp | exit_code | restart_count | runtime
  TS=$(date '+%Y-%m-%d %H:%M:%S')
  echo "$TS | exit=$EXIT_CODE | restart=$((RESTART_COUNT + 1)) | runtime=${RUNTIME}s" >> "$RESTART_LOG"

  RESTART_COUNT=$((RESTART_COUNT + 1))
  if [ "$RESTART_COUNT" -ge "$MAX_RESTARTS" ]; then
    echo "[SquidSquad] Max restarts ($MAX_RESTARTS) reached. Stopping."
    echo "error|Max restarts reached" > "$STATE_FILE"
    break
  fi

  if [ "$RUNTIME" -lt "$MIN_RUNTIME_SECONDS" ]; then
    # Fast crash — exponential backoff
    COOLDOWN=$((COOLDOWN_BASE * (1 << (RESTART_COUNT - 1))))
    [ "$COOLDOWN" -gt "$COOLDOWN_MAX" ] && COOLDOWN=$COOLDOWN_MAX
    echo "[SquidSquad] Fast exit (${RUNTIME}s, exit $EXIT_CODE). Backoff ${COOLDOWN}s..."
    echo "waiting|Restart backoff (${COOLDOWN}s)" > "$STATE_FILE"
    sleep "$COOLDOWN"
  else
    # Healthy run — reset counter, standard 10s cooldown
    RESTART_COUNT=0
    echo "[SquidSquad] Agent exited after ${RUNTIME}s (exit $EXIT_CODE). Restarting in 10s..."
    echo "restarting|Restarting in 10s..." > "$STATE_FILE"
    sleep 10
  fi
done
