# GENERATED by compose.py boot skill. DO NOT EDIT.
# Regenerate: python references/scripts/compose.py boot skill
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$repoRoot = git rev-parse --show-toplevel
Set-Location $repoRoot

# Parse --name flag (optional override for agent alias)
$AgentName = ""
for ($i = 0; $i -lt $args.Count; $i++) {
    if ($args[$i] -eq "--name" -and ($i + 1) -lt $args.Count) {
        $AgentName = $args[$i + 1]
        break
    }
}

# Read alias from config if no --name override
if (-not $AgentName) {
    try {
        $AgentName = (python references/scripts/config.py alias skill 2>$null).Trim()
    } catch {
        $AgentName = "squidsquad-skill"
    }
    if (-not $AgentName) { $AgentName = "squidsquad-skill" }
}

if (Test-Path .squidsquad) {
    $config = Get-Content .squidsquad/config.md -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
    $v = if ($config -match '(\d+\.\d+[\.\d]*)') { $Matches[1] } else { '?' }

    Write-Host ""
    Write-Host "      ▗▄▖"
    Write-Host "     ▟█ █▙"
    Write-Host "    ▐█• •█▌"
    Write-Host "   ███████"
    Write-Host "   ▐█████▌"
    Write-Host "    ▐▌▐▌▐▌"
    Write-Host "  S Q U I D S Q U A D   v$v  -  $AgentName"
    Write-Host ""
}

# Inject permissions from template into settings.json
$injectScript = Join-Path $repoRoot ".squidsquad/inject-permissions.ps1"
if (Test-Path $injectScript) { & $injectScript }

# Register this agent in config.md
try { python references/scripts/config.py sync-agents 2>$null } catch {}

# Write role for statusline (not used for auto-boot -- system prompt handles that)
"skill" | Set-Content .squidsquad/.active-role -NoNewline

# --- PID lock: prevent double-start ---
$RoleDir = ".squidsquad/skill"
$PidFile = "$RoleDir/.pid"
$StopFile = "$RoleDir/.stop"
$RestartSentinel = "$RoleDir/.restart"
$RestartLog = "$RoleDir/restart-log.txt"
$StateFile = "$RoleDir/current-state"

if (-not (Test-Path $RoleDir)) { New-Item -ItemType Directory -Path $RoleDir -Force | Out-Null }

if (Test-Path $PidFile) {
    $oldPid = (Get-Content $PidFile -ErrorAction SilentlyContinue | Select-Object -First 1)
    if ($oldPid) {
        $running = $null
        try { $running = Get-Process -Id $oldPid -ErrorAction SilentlyContinue } catch {}
        if ($running) {
            Write-Host "[SquidSquad] Agent skill already running (PID $oldPid). Aborting."
            Write-Host "[SquidSquad] If this is stale, remove $PidFile manually."
            exit 1
        }
    }
    # Stale — clean up
    Remove-Item $PidFile -ErrorAction SilentlyContinue
}
$PID | Set-Content $PidFile -NoNewline

# --- Cleanup on exit: remove PID file ---
try {
    # --- Auto-restart wrapper ---
    $MaxRestarts = 50
    $RestartCount = 0
    $CooldownBase = 2
    $CooldownMax = 300
    $MinRuntimeSeconds = 120

    while ($true) {
        # Reset status bar for a fresh session
        Remove-Item $StateFile -ErrorAction SilentlyContinue
        "idle|Initializing..." | Set-Content $StateFile -NoNewline

        $startTime = Get-Date

        $sysPrompt = "SQUIDSQUAD_ROLE=skill"
        $initMsg = "start the loop"
        claude --dangerously-skip-permissions --name "$AgentName" --append-system-prompt "$sysPrompt" "$initMsg"
        $exitCode = $LASTEXITCODE

        $runtime = [int]((Get-Date) - $startTime).TotalSeconds

        # Check for stop sentinel file
        if (Test-Path $StopFile) {
            Write-Host "[SquidSquad] Stop file detected. Not restarting."
            Remove-Item $StopFile -ErrorAction SilentlyContinue
            "stopped|Agent stopped by user" | Set-Content $StateFile -NoNewline
            break
        }

        # Check for self-restart sentinel (agent requested restart)
        if (Test-Path $RestartSentinel) {
            $reason = (Get-Content $RestartSentinel -ErrorAction SilentlyContinue | Select-Object -First 1)
            if (-not $reason) { $reason = "unknown" }
            Remove-Item $RestartSentinel -ErrorAction SilentlyContinue
            $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
            "$ts | exit=$exitCode | self-restart | reason=$reason | runtime=${runtime}s" | Add-Content $RestartLog
            Write-Host "[SquidSquad] Self-restart requested: $reason. Restarting immediately..."
            "restarting|Self-restart: $reason" | Set-Content $StateFile -NoNewline
            $RestartCount = 0
            Start-Sleep -Seconds 2
            continue
        }

        # Append restart log entry
        $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        "$ts | exit=$exitCode | restart=$($RestartCount + 1) | runtime=${runtime}s" | Add-Content $RestartLog

        $RestartCount++
        if ($RestartCount -ge $MaxRestarts) {
            Write-Host "[SquidSquad] Max restarts ($MaxRestarts) reached. Stopping."
            "error|Max restarts reached" | Set-Content $StateFile -NoNewline
            break
        }

        if ($runtime -lt $MinRuntimeSeconds) {
            # Fast crash — exponential backoff
            $cooldown = [Math]::Min($CooldownBase * [Math]::Pow(2, $RestartCount - 1), $CooldownMax)
            $cooldown = [int]$cooldown
            Write-Host "[SquidSquad] Fast exit (${runtime}s, exit $exitCode). Backoff ${cooldown}s..."
            "waiting|Restart backoff (${cooldown}s)" | Set-Content $StateFile -NoNewline
            Start-Sleep -Seconds $cooldown
        } else {
            # Healthy run — reset counter, standard 10s cooldown
            $RestartCount = 0
            Write-Host "[SquidSquad] Agent exited after ${runtime}s (exit $exitCode). Restarting in 10s..."
            "restarting|Restarting in 10s..." | Set-Content $StateFile -NoNewline
            Start-Sleep -Seconds 10
        }
    }
} finally {
    Remove-Item $PidFile -ErrorAction SilentlyContinue
}
