#!/usr/bin/env python3
"""SquidSquad add-role — clone, configure, and boot an agent role.

Creates a new clone for an agent role, configures it, syncs .local-config
across all clones, and optionally boots the agent.

Usage:
    python scripts/add_role.py <role> [--target <path>] [--boot] [--force] [--dry-run]
    python scripts/add_role.py --register-existing <role> <path>
    python scripts/add_role.py --list
    python scripts/add_role.py --help

Examples:
    python scripts/add_role.py qa                    # Clone to ../SquidSquad-qa
    python scripts/add_role.py skill --boot          # Clone and start agent
    python scripts/add_role.py qa --dry-run          # Preview without changes
    python scripts/add_role.py --register-existing skill /path/to/clone
    python scripts/add_role.py --list                # Show all configured clones
"""

import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
SQUIDSQUAD_DIR = REPO_ROOT / ".squidsquad"
LOCAL_CONFIG = SQUIDSQUAD_DIR / ".local-config"
LOCK_FILE = SQUIDSQUAD_DIR / ".add-role.lock"


def _run(cmd_list, cwd=None, check=True):
    """Run a command and return result."""
    return subprocess.run(
        cmd_list, capture_output=True, text=True,
        encoding="utf-8", errors="replace",
        check=check, cwd=str(cwd or REPO_ROOT),
    )


def _get_project_name():
    """Read project name from config.md."""
    try:
        sys.path.insert(0, str(SCRIPT_DIR))
        from config import get_field
        return get_field("project-name")
    except (ImportError, SystemExit):
        return REPO_ROOT.name


def _get_configured_agents():
    """Read dev-agents + infrastructure roles from config."""
    try:
        sys.path.insert(0, str(SCRIPT_DIR))
        from config import get_field
        agents_str = get_field("dev-agents")
        agents = [a.strip() for a in agents_str.split(",") if a.strip()]
        # Fixed team: PM + QA + DM always present (#6261)
        for role in ("pm", "qa", "dm"):
            if role not in agents:
                agents.append(role)
        return agents
    except (ImportError, SystemExit):
        return ["pm"]


def _validate_role(role):
    """Check that the role exists in config.md or has a role template."""
    configured = _get_configured_agents()
    roles_dir = REPO_ROOT / "references" / "roles"
    has_template = (roles_dir / role / "CLAUDE.md").exists()

    if role in configured:
        return True
    if has_template:
        return True
    return False


def _parse_local_config(config_path=None):
    """Parse .local-config -> {role: path_str}."""
    path = config_path or LOCAL_CONFIG
    if not path.exists():
        return {}
    result = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"-\s*\*\*([\w-]+)\*\*:\s*(.+)", line)
        if m:
            result[m.group(1).strip()] = m.group(2).strip()
    return result


def _write_local_config(agents_map, target_path=None):
    """Write .local-config atomically."""
    path = target_path or LOCAL_CONFIG
    lines = [
        "# Agent clone paths — auto-generated by add_role.py",
        "# Format: - **role**: /absolute/path/to/clone",
        "",
    ]
    for role in sorted(agents_map):
        lines.append(f"- **{role}**: {agents_map[role]}")

    tmp = path.parent / ".local-config.tmp"
    tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tmp.replace(path)


def _sync_local_config(agents_map):
    """Write .local-config to ALL known clone roots."""
    seen_roots = set()
    for role, clone_path in agents_map.items():
        root = Path(clone_path)
        if root in seen_roots:
            continue
        seen_roots.add(root)
        config_path = root / ".squidsquad" / ".local-config"
        if config_path.parent.exists():
            _write_local_config(agents_map, config_path)
            print(f"  Synced .local-config in {root}")


def _get_upstream_url():
    """Get the upstream (GitHub) URL from the primary repo's origin remote."""
    result = _run(["git", "remote", "get-url", "origin"], check=False)
    if result.returncode == 0:
        return result.stdout.strip()
    return None


def _fix_clone_remote(clone_path, upstream_url):
    """Reconfigure a clone's origin to point at the upstream URL.

    After git clone --local, origin points to the local filesystem path.
    This replaces it with the actual upstream URL so the clone can see
    branches pushed to GitHub by other agents.
    """
    if not upstream_url:
        return False
    result = _run(
        ["git", "remote", "set-url", "origin", upstream_url],
        cwd=clone_path, check=False,
    )
    if result.returncode != 0:
        print(f"  WARNING: Failed to set origin URL: {result.stderr}", file=sys.stderr)
        return False
    # Fetch to populate remote refs
    _run(["git", "fetch", "origin"], cwd=clone_path, check=False)
    return True


def _acquire_lock():
    """Acquire a lock file for concurrency protection. Returns True on success."""
    try:
        LOCK_FILE.parent.mkdir(parents=True, exist_ok=True)
        # Use exclusive create — fails if file exists
        fd = LOCK_FILE.open("x")
        try:
            fd.write(str(os.getpid()))
            fd.close()
        except OSError:
            # Write/close failed — remove the empty lock file to avoid
            # leaving a stale lock that blocks all future calls (#4093).
            fd.close()
            _release_lock()
            return False
        return True
    except FileExistsError:
        return False


def _release_lock():
    """Release the lock file."""
    try:
        LOCK_FILE.unlink(missing_ok=True)
    except OSError:
        pass


def add_role(role, target=None, boot=False, force=False, dry_run=False):
    """Clone repo, configure role, sync .local-config, optionally boot."""
    # Validate role exists
    if not _validate_role(role):
        print(f"ERROR: Role '{role}' not found in config.md or references/roles/", file=sys.stderr)
        return 1

    # Check for duplicate role registration (TC-9)
    if not force:
        existing = _parse_local_config()
        if role in existing:
            print(
                f"ERROR: Role '{role}' is already registered at {existing[role]}",
                file=sys.stderr,
            )
            print("Use --force to overwrite the existing registration.", file=sys.stderr)
            return 1

    project_name = _get_project_name()

    # Default target: sibling directory ProjectName-<role>
    if target is None:
        target = REPO_ROOT.parent / f"{project_name}-{role}"
    else:
        target = Path(target).resolve()

    if dry_run:
        print(f"[dry-run] Would clone '{role}' to {target}")
        print(f"[dry-run] Would deploy {role} CLAUDE.md + SOUL.md")
        print(f"[dry-run] Would generate boot scripts")
        print(f"[dry-run] Would sync .local-config across all clones")
        if boot:
            print(f"[dry-run] Would boot agent via start-{role}.[sh|ps1]")
        return 0

    print(f"Adding role '{role}' at {target}")

    # Safety checks
    if target.exists() and not force:
        print(f"ERROR: Target directory exists: {target}", file=sys.stderr)
        print("Use --force to overwrite or --register-existing to add an existing clone.", file=sys.stderr)
        return 1

    # Concurrency lock
    if not _acquire_lock():
        print("ERROR: Another add_role operation is in progress (lock file exists).", file=sys.stderr)
        print(f"If this is stale, delete {LOCK_FILE}", file=sys.stderr)
        return 1

    try:
        # Check for uncommitted changes
        status = _run(["git", "status", "--porcelain"], check=False)
        if status.stdout.strip():
            print("WARNING: Source repo has uncommitted changes. They will NOT be in the clone.", file=sys.stderr)

        # Write .active-role BEFORE cloning (so the clone picks it up)
        active_role_path = SQUIDSQUAD_DIR / role / ".active-role-pending"
        # We'll write it in the clone after cloning instead

        # Clone with --local for speed (hardlinks)
        print(f"  Cloning to {target}...")
        if target.exists() and force:
            shutil.rmtree(target)
        _run(["git", "clone", "--local", str(REPO_ROOT), str(target)])

        # Fix origin remote: --local sets it to local path, we need upstream URL
        upstream_url = _get_upstream_url()
        if upstream_url:
            print(f"  Setting origin to upstream: {upstream_url}")
            _fix_clone_remote(target, upstream_url)
        else:
            print("  WARNING: Could not determine upstream URL — clone origin may be wrong", file=sys.stderr)

        # Write .active-role in the clone FIRST (before deploy/boot)
        clone_squid = target / ".squidsquad"
        clone_squid.mkdir(parents=True, exist_ok=True)
        (clone_squid / ".active-role").write_text(f"{role}\n", encoding="utf-8")

        # Configure the clone: deploy role CLAUDE.md + SOUL.md
        print(f"  Deploying {role} in clone...")
        _run(
            [sys.executable, str(SCRIPT_DIR / "compose.py"), "deploy", role],
            cwd=target,
        )

        # Generate boot scripts
        print(f"  Generating boot scripts...")
        _run(
            [sys.executable, str(SCRIPT_DIR / "compose.py"), "boot", role],
            cwd=target,
        )

        # Build updated agents map
        agents_map = _parse_local_config()
        agents_map[role] = str(target)
        # Ensure source is in the map too
        current_roles = _get_configured_agents()
        for r in current_roles:
            if r not in agents_map:
                agents_map[r] = str(REPO_ROOT)

        # Sync .local-config to ALL clones (including the new one)
        print(f"  Syncing .local-config across all clones...")
        _sync_local_config(agents_map)

        print(f"  Role '{role}' configured at {target}")

        # Optionally boot
        if boot:
            print(f"  Booting {role}...")
            boot_script = target / ".squidsquad" / f"start-{role}"
            if sys.platform == "win32":
                ps1 = Path(f"{boot_script}.ps1")
                if ps1.exists():
                    _run(["powershell", "-File", str(ps1)], cwd=target, check=False)
                else:
                    print(f"  WARNING: No boot script at {ps1}", file=sys.stderr)
            else:
                sh = Path(f"{boot_script}.sh")
                if sh.exists():
                    _run(["bash", str(sh)], cwd=target, check=False)
                else:
                    print(f"  WARNING: No boot script at {sh}", file=sys.stderr)

        print(f"\nDone. To start the agent manually:")
        print(f"  cd {target}")
        if sys.platform == "win32":
            print(f"  .squidsquad\\start-{role}.ps1")
        else:
            print(f"  bash .squidsquad/start-{role}.sh")

        return 0

    finally:
        _release_lock()


def register_existing(role, clone_path):
    """Register an existing clone in .local-config.

    Also verifies the clone's origin remote points at the upstream URL
    (not a local filesystem path) and fixes it if needed.
    """
    clone_path = Path(clone_path).resolve()
    if not clone_path.exists():
        print(f"ERROR: Path does not exist: {clone_path}", file=sys.stderr)
        return 1
    if not (clone_path / ".squidsquad").exists():
        print(f"ERROR: Not a SquidSquad clone (no .squidsquad/): {clone_path}", file=sys.stderr)
        return 1

    # Verify/fix remote
    upstream_url = _get_upstream_url()
    if upstream_url:
        clone_origin = _run(
            ["git", "remote", "get-url", "origin"],
            cwd=clone_path, check=False,
        )
        clone_url = clone_origin.stdout.strip() if clone_origin.returncode == 0 else ""
        if clone_url != upstream_url:
            print(f"  Fixing origin: {clone_url} → {upstream_url}")
            _fix_clone_remote(clone_path, upstream_url)

    agents_map = _parse_local_config()
    agents_map[role] = str(clone_path)

    current_roles = _get_configured_agents()
    for r in current_roles:
        if r not in agents_map:
            agents_map[r] = str(REPO_ROOT)

    _sync_local_config(agents_map)
    print(f"Registered '{role}' at {clone_path}")
    return 0


def list_clones():
    """List all configured agent clones."""
    agents_map = _parse_local_config()
    if not agents_map:
        print("No clones configured in .local-config")
        return
    for role in sorted(agents_map):
        path = agents_map[role]
        exists = Path(path).exists()
        status = "OK" if exists else "MISSING"
        print(f"  {role}: {path} [{status}]")


def main():
    args = sys.argv[1:]
    if not args or args[0] in ("--help", "-h"):
        print(__doc__)
        return 0

    if args[0] == "--list":
        list_clones()
        return 0

    if args[0] == "--register-existing":
        if len(args) < 3:
            print("Usage: add_role.py --register-existing <role> <path>", file=sys.stderr)
            return 1
        return register_existing(args[1], args[2])

    # Main flow: add_role <role> [--target <path>] [--boot] [--force] [--dry-run]
    role = args[0]
    target = None
    boot = False
    force = False
    dry_run = False

    i = 1
    while i < len(args):
        if args[i] == "--target" and i + 1 < len(args):
            target = args[i + 1]
            i += 2
        elif args[i] == "--boot":
            boot = True
            i += 1
        elif args[i] == "--force":
            force = True
            i += 1
        elif args[i] == "--dry-run":
            dry_run = True
            i += 1
        else:
            print(f"Unknown argument: {args[i]}", file=sys.stderr)
            return 1

    return add_role(role, target=target, boot=boot, force=force, dry_run=dry_run)


if __name__ == "__main__":
    sys.exit(main())
