#!/usr/bin/env python3
"""SquidSquad add-role — clone, configure, and boot an agent role.

Creates a new clone for an agent role, configures it, syncs .local-config
across all clones, and optionally boots the agent.

Usage:
    python scripts/add_role.py <role> [--target <path>] [--boot] [--force]
    python scripts/add_role.py --register-existing <role> <path>
    python scripts/add_role.py --list
    python scripts/add_role.py --help

Examples:
    python scripts/add_role.py qa                    # Clone to ../SquidSquad-qa
    python scripts/add_role.py skill --boot          # Clone and start agent
    python scripts/add_role.py --register-existing skill /path/to/clone
    python scripts/add_role.py --list                # Show all configured clones
"""

import json
import shutil
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
SQUIDSQUAD_DIR = REPO_ROOT / ".squidsquad"
LOCAL_CONFIG = SQUIDSQUAD_DIR / ".local-config"


def _run(cmd_list, cwd=None, check=True):
    """Run a command and return result."""
    return subprocess.run(
        cmd_list, capture_output=True, text=True,
        encoding="utf-8", errors="replace",
        check=check, cwd=str(cwd or REPO_ROOT),
    )


def _get_project_name():
    """Read project name from config.md."""
    try:
        sys.path.insert(0, str(SCRIPT_DIR))
        from config import get_field
        return get_field("project-name")
    except (ImportError, SystemExit):
        return REPO_ROOT.name


def _get_configured_agents():
    """Read dev-agents + infrastructure roles from config."""
    try:
        sys.path.insert(0, str(SCRIPT_DIR))
        from config import get_field
        agents_str = get_field("dev-agents")
        agents = [a.strip() for a in agents_str.split(",") if a.strip()]
        agents.append("pm")
        # Check for DM
        if (SQUIDSQUAD_DIR / "dm").exists():
            agents.append("dm")
        return agents
    except (ImportError, SystemExit):
        return ["pm"]


def _parse_local_config(config_path=None):
    """Parse .local-config -> {role: path_str}."""
    path = config_path or LOCAL_CONFIG
    if not path.exists():
        return {}
    result = {}
    import re
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"-\s*\*\*(\w+)\*\*:\s*(.+)", line)
        if m:
            result[m.group(1).strip()] = m.group(2).strip()
    return result


def _write_local_config(agents_map, target_path=None):
    """Write .local-config atomically."""
    path = target_path or LOCAL_CONFIG
    lines = [
        "# Agent clone paths — auto-generated by add_role.py",
        "# Format: - **role**: /absolute/path/to/clone",
        "",
    ]
    for role in sorted(agents_map):
        lines.append(f"- **{role}**: {agents_map[role]}")

    tmp = path.parent / ".local-config.tmp"
    tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tmp.replace(path)


def _sync_local_config(agents_map):
    """Write .local-config to ALL known clone roots."""
    seen_roots = set()
    for role, clone_path in agents_map.items():
        root = Path(clone_path)
        if root in seen_roots:
            continue
        seen_roots.add(root)
        config_path = root / ".squidsquad" / ".local-config"
        if config_path.parent.exists():
            _write_local_config(agents_map, config_path)
            print(f"  Synced .local-config in {root}")


def add_role(role, target=None, boot=False, force=False):
    """Clone repo, configure role, sync .local-config, optionally boot."""
    project_name = _get_project_name()

    # Default target: sibling directory ProjectName-<role>
    if target is None:
        target = REPO_ROOT.parent / f"{project_name}-{role}"
    else:
        target = Path(target).resolve()

    print(f"Adding role '{role}' at {target}")

    # Safety checks
    if target.exists() and not force:
        print(f"ERROR: Target directory exists: {target}", file=sys.stderr)
        print("Use --force to overwrite or --register-existing to add an existing clone.", file=sys.stderr)
        return 1

    # Check for uncommitted changes
    status = _run(["git", "status", "--porcelain"], check=False)
    if status.stdout.strip():
        print("WARNING: Source repo has uncommitted changes. They will NOT be in the clone.", file=sys.stderr)

    # Clone with --local for speed (hardlinks)
    print(f"  Cloning to {target}...")
    if target.exists() and force:
        shutil.rmtree(target)
    _run(["git", "clone", "--local", str(REPO_ROOT), str(target)])

    # Configure the clone: deploy role CLAUDE.md + SOUL.md
    print(f"  Deploying {role} in clone...")
    _run(
        [sys.executable, str(SCRIPT_DIR / "compose.py"), "deploy", role],
        cwd=target,
    )

    # Generate boot scripts
    print(f"  Generating boot scripts...")
    _run(
        [sys.executable, str(SCRIPT_DIR / "compose.py"), "boot", role],
        cwd=target,
    )

    # Write .active-role
    active_role_path = target / ".squidsquad" / ".active-role"
    active_role_path.write_text(f"{role}\n", encoding="utf-8")

    # Build updated agents map
    agents_map = _parse_local_config()
    agents_map[role] = str(target)
    # Ensure source is in the map too
    current_roles = _get_configured_agents()
    for r in current_roles:
        if r not in agents_map:
            agents_map[r] = str(REPO_ROOT)

    # Sync .local-config to ALL clones (including the new one)
    print(f"  Syncing .local-config across all clones...")
    _sync_local_config(agents_map)

    print(f"  Role '{role}' configured at {target}")

    # Optionally boot
    if boot:
        print(f"  Booting {role}...")
        boot_script = target / ".squidsquad" / f"start-{role}"
        # Try .ps1 on Windows, .sh elsewhere
        if sys.platform == "win32":
            ps1 = Path(f"{boot_script}.ps1")
            if ps1.exists():
                _run(["powershell", "-File", str(ps1)], cwd=target, check=False)
            else:
                print(f"  WARNING: No boot script at {ps1}", file=sys.stderr)
        else:
            sh = Path(f"{boot_script}.sh")
            if sh.exists():
                _run(["bash", str(sh)], cwd=target, check=False)
            else:
                print(f"  WARNING: No boot script at {sh}", file=sys.stderr)

    print(f"\nDone. To start the agent manually:")
    print(f"  cd {target}")
    if sys.platform == "win32":
        print(f"  .squidsquad\\start-{role}.ps1")
    else:
        print(f"  bash .squidsquad/start-{role}.sh")

    return 0


def register_existing(role, clone_path):
    """Register an existing clone in .local-config."""
    clone_path = Path(clone_path).resolve()
    if not clone_path.exists():
        print(f"ERROR: Path does not exist: {clone_path}", file=sys.stderr)
        return 1
    if not (clone_path / ".squidsquad").exists():
        print(f"ERROR: Not a SquidSquad clone (no .squidsquad/): {clone_path}", file=sys.stderr)
        return 1

    agents_map = _parse_local_config()
    agents_map[role] = str(clone_path)

    # Ensure source is in the map
    current_roles = _get_configured_agents()
    for r in current_roles:
        if r not in agents_map:
            agents_map[r] = str(REPO_ROOT)

    _sync_local_config(agents_map)
    print(f"Registered '{role}' at {clone_path}")
    return 0


def list_clones():
    """List all configured agent clones."""
    agents_map = _parse_local_config()
    if not agents_map:
        print("No clones configured in .local-config")
        return
    for role in sorted(agents_map):
        path = agents_map[role]
        exists = Path(path).exists()
        status = "OK" if exists else "MISSING"
        print(f"  {role}: {path} [{status}]")


def main():
    args = sys.argv[1:]
    if not args or args[0] in ("--help", "-h"):
        print(__doc__)
        return 0

    if args[0] == "--list":
        list_clones()
        return 0

    if args[0] == "--register-existing":
        if len(args) < 3:
            print("Usage: add_role.py --register-existing <role> <path>", file=sys.stderr)
            return 1
        return register_existing(args[1], args[2])

    # Main flow: add_role <role> [--target <path>] [--boot] [--force]
    role = args[0]
    target = None
    boot = False
    force = False

    i = 1
    while i < len(args):
        if args[i] == "--target" and i + 1 < len(args):
            target = args[i + 1]
            i += 2
        elif args[i] == "--boot":
            boot = True
            i += 1
        elif args[i] == "--force":
            force = True
            i += 1
        else:
            print(f"Unknown argument: {args[i]}", file=sys.stderr)
            return 1

    return add_role(role, target=target, boot=boot, force=force)


if __name__ == "__main__":
    sys.exit(main())
